<?php
	require_once(__DIR__."/constants.php");
	require_once(__DIR__."/settings.php");
	require_once(__DIR__."/util.php");
	require_once(__DIR__."/db.php");
	require_once(__DIR__."/token.php");
	require_once(__DIR__."/endpoints.php");
	require_once(__DIR__."/request-exception.php");
	require_once(__DIR__."/request-util.php");
	require_once(__DIR__."/request-handler.php");

	require_once(__DIR__."/../endpoints/state.php");
	require_once(__DIR__."/../endpoints/users.php");
	require_once(__DIR__."/../endpoints/tokens.php");
	//require_once(__DIR__."/../endpoints/datasets.php");
	//require_once(__DIR__."/../endpoints/datasets-tokens.php");
	//require_once(__DIR__."/../endpoints/datasets-nodes.php");
	require_once(__DIR__."/../endpoints/nodes.php");
	require_once(__DIR__."/../endpoints/sensors.php");
